apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxcomponent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxcomponent
  template:
    metadata:
      labels:
        app: mxcomponent
    spec:
      containers:
      - name: mxcomponent
        image:  348096830755.dkr.ecr.us-east-2.amazonaws.com/tagit:mxcomponent_1
        ports:
        - containerPort: 8080
