apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxprocess
  template:
    metadata:
      labels:
        app: mxprocess
    spec:
      containers:
      - name: mxprocess
        image: 348096830755.dkr.ecr.us-east-2.amazonaws.com/tagit:process_1
        ports:
        - containerPort: 8080
